from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from vidispine.api.access_api import AccessApi
from vidispine.api.access_key_api import AccessKeyApi
from vidispine.api.analyze_api import AnalyzeApi
from vidispine.api.audit_log_api import AuditLogApi
from vidispine.api.auto_import_api import AutoImportApi
from vidispine.api.auto_projection_api import AutoProjectionApi
from vidispine.api.autocomplete_api import AutocompleteApi
from vidispine.api.collection_api import CollectionApi
from vidispine.api.configuration_api import ConfigurationApi
from vidispine.api.conform_api import ConformApi
from vidispine.api.cost_estimation_api import CostEstimationApi
from vidispine.api.dataset_api import DatasetApi
from vidispine.api.deletion_lock_api import DeletionLockApi
from vidispine.api.document_api import DocumentApi
from vidispine.api.eidr_api import EidrApi
from vidispine.api.entity_site_rule_api import EntitySiteRuleApi
from vidispine.api.entity_storage_rule_api import EntityStorageRuleApi
from vidispine.api.export_location_api import ExportLocationApi
from vidispine.api.external_id_api import ExternalIdApi
from vidispine.api.external_id_namespace_api import ExternalIdNamespaceApi
from vidispine.api.field_access_api import FieldAccessApi
from vidispine.api.field_group_access_api import FieldGroupAccessApi
from vidispine.api.field_group_external_id_api import FieldGroupExternalIdApi
from vidispine.api.file_api import FileApi
from vidispine.api.global_metadata_api import GlobalMetadataApi
from vidispine.api.group_api import GroupApi
from vidispine.api.import_api import ImportApi
from vidispine.api.import_settings_api import ImportSettingsApi
from vidispine.api.item_api import ItemApi
from vidispine.api.item_bulky_metadata_api import ItemBulkyMetadataApi
from vidispine.api.item_lock_api import ItemLockApi
from vidispine.api.javascript_api import JavascriptApi
from vidispine.api.job_api import JobApi
from vidispine.api.library_api import LibraryApi
from vidispine.api.license_api import LicenseApi
from vidispine.api.loudness_api import LoudnessApi
from vidispine.api.metadata_api import MetadataApi
from vidispine.api.metadata_field_api import MetadataFieldApi
from vidispine.api.metadata_field_groups_api import MetadataFieldGroupsApi
from vidispine.api.metadata_lock_api import MetadataLockApi
from vidispine.api.metadata_migration_api import MetadataMigrationApi
from vidispine.api.metadata_schema_api import MetadataSchemaApi
from vidispine.api.notification_api import NotificationApi
from vidispine.api.poster_resource_api import PosterResourceApi
from vidispine.api.project_collection_api import ProjectCollectionApi
from vidispine.api.project_version_api import ProjectVersionApi
from vidispine.api.projection_api import ProjectionApi
from vidispine.api.quota_rule_api import QuotaRuleApi
from vidispine.api.reindex_api import ReindexApi
from vidispine.api.relation_api import RelationApi
from vidispine.api.resource_api import ResourceApi
from vidispine.api.scheduled_request_api import ScheduledRequestApi
from vidispine.api.search_api import SearchApi
from vidispine.api.selftest_api import SelftestApi
from vidispine.api.sequence_api import SequenceApi
from vidispine.api.server_agent_api import ServerAgentApi
from vidispine.api.shape_api import ShapeApi
from vidispine.api.shape_bulky_metadata_api import ShapeBulkyMetadataApi
from vidispine.api.shape_tag_api import ShapeTagApi
from vidispine.api.site_api import SiteApi
from vidispine.api.site_rule_api import SiteRuleApi
from vidispine.api.storage_api import StorageApi
from vidispine.api.storage_group_api import StorageGroupApi
from vidispine.api.storage_method_api import StorageMethodApi
from vidispine.api.storage_name_rule_api import StorageNameRuleApi
from vidispine.api.storage_rule_api import StorageRuleApi
from vidispine.api.system_api import SystemApi
from vidispine.api.task_definition_api import TaskDefinitionApi
from vidispine.api.task_group_api import TaskGroupApi
from vidispine.api.thumbnail_resource_api import ThumbnailResourceApi
from vidispine.api.timeline_api import TimelineApi
from vidispine.api.transfer_api import TransferApi
from vidispine.api.transfer_log_api import TransferLogApi
from vidispine.api.user_api import UserApi
from vidispine.api.user_alias_api import UserAliasApi
from vidispine.api.user_token_api import UserTokenApi
from vidispine.api.vidispine_logs_api import VidispineLogsApi
from vidispine.api.vidispine_service_api import VidispineServiceApi
from vidispine.api.waveform_api import WaveformApi
