# coding: utf-8

"""
    Vidispine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.x
    Contact: info@vidispine.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six
from . import *

class AccessControlTypeOperation(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'shape': 'AccessControlShapeType',
        'uri': 'AccessControlUriType',
        'metadata': 'AccessControlMetadataType'
    }

    attribute_map = {
        'shape': 'shape',
        'uri': 'uri',
        'metadata': 'metadata'
    }

    def __init__(self, shape=None, uri=None, metadata=None):  # noqa: E501
        """AccessControlTypeOperation - a model defined in OpenAPI"""  # noqa: E501

        self._shape = None
        self._uri = None
        self._metadata = None
        self.discriminator = None

        if shape is not None:
            self.shape = shape
        if uri is not None:
            self.uri = uri
        if metadata is not None:
            self.metadata = metadata

    @property
    def shape(self):
        """Gets the shape of this AccessControlTypeOperation.  # noqa: E501


        :return: The shape of this AccessControlTypeOperation.  # noqa: E501
        :rtype: AccessControlShapeType
        """
        return self._shape

    @shape.setter
    def shape(self, shape):
        """Sets the shape of this AccessControlTypeOperation.


        :param shape: The shape of this AccessControlTypeOperation.  # noqa: E501
        :type: AccessControlShapeType
        """

        self._shape = shape

    @property
    def uri(self):
        """Gets the uri of this AccessControlTypeOperation.  # noqa: E501


        :return: The uri of this AccessControlTypeOperation.  # noqa: E501
        :rtype: AccessControlUriType
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this AccessControlTypeOperation.


        :param uri: The uri of this AccessControlTypeOperation.  # noqa: E501
        :type: AccessControlUriType
        """

        self._uri = uri

    @property
    def metadata(self):
        """Gets the metadata of this AccessControlTypeOperation.  # noqa: E501


        :return: The metadata of this AccessControlTypeOperation.  # noqa: E501
        :rtype: AccessControlMetadataType
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this AccessControlTypeOperation.


        :param metadata: The metadata of this AccessControlTypeOperation.  # noqa: E501
        :type: AccessControlMetadataType
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccessControlTypeOperation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
