# coding: utf-8

"""
    Vidispine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.x
    Contact: info@vidispine.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six
from . import *

class ComplexJobMixType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'gain': 'float',
        'id': 'int',
        'stream': 'int',
        'channel': 'int'
    }

    attribute_map = {
        'gain': 'gain',
        'id': 'id',
        'stream': 'stream',
        'channel': 'channel'
    }

    def __init__(self, gain=None, id=None, stream=None, channel=None):  # noqa: E501
        """ComplexJobMixType - a model defined in OpenAPI"""  # noqa: E501

        self._gain = None
        self._id = None
        self._stream = None
        self._channel = None
        self.discriminator = None

        self.gain = gain
        self.id = id
        self.stream = stream
        self.channel = channel

    @property
    def gain(self):
        """Gets the gain of this ComplexJobMixType.  # noqa: E501


        :return: The gain of this ComplexJobMixType.  # noqa: E501
        :rtype: float
        """
        return self._gain

    @gain.setter
    def gain(self, gain):
        """Sets the gain of this ComplexJobMixType.


        :param gain: The gain of this ComplexJobMixType.  # noqa: E501
        :type: float
        """
        if gain is None:
            raise ValueError("Invalid value for `gain`, must not be `None`")  # noqa: E501

        self._gain = gain

    @property
    def id(self):
        """Gets the id of this ComplexJobMixType.  # noqa: E501


        :return: The id of this ComplexJobMixType.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ComplexJobMixType.


        :param id: The id of this ComplexJobMixType.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def stream(self):
        """Gets the stream of this ComplexJobMixType.  # noqa: E501


        :return: The stream of this ComplexJobMixType.  # noqa: E501
        :rtype: int
        """
        return self._stream

    @stream.setter
    def stream(self, stream):
        """Sets the stream of this ComplexJobMixType.


        :param stream: The stream of this ComplexJobMixType.  # noqa: E501
        :type: int
        """
        if stream is None:
            raise ValueError("Invalid value for `stream`, must not be `None`")  # noqa: E501

        self._stream = stream

    @property
    def channel(self):
        """Gets the channel of this ComplexJobMixType.  # noqa: E501


        :return: The channel of this ComplexJobMixType.  # noqa: E501
        :rtype: int
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this ComplexJobMixType.


        :param channel: The channel of this ComplexJobMixType.  # noqa: E501
        :type: int
        """
        if channel is None:
            raise ValueError("Invalid value for `channel`, must not be `None`")  # noqa: E501

        self._channel = channel

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComplexJobMixType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
