# coding: utf-8

"""
    Vidispine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.x
    Contact: info@vidispine.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six
from . import *

class DMS1TypePartition(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'material_package': 'list[DMS1TypeMaterialPackage]',
        'offset': 'int'
    }

    attribute_map = {
        'material_package': 'materialPackage',
        'offset': 'offset'
    }

    def __init__(self, material_package=None, offset=None):  # noqa: E501
        """DMS1TypePartition - a model defined in OpenAPI"""  # noqa: E501

        self._material_package = None
        self._offset = None
        self.discriminator = None

        if material_package is not None:
            self.material_package = material_package
        if offset is not None:
            self.offset = offset

    @property
    def material_package(self):
        """Gets the material_package of this DMS1TypePartition.  # noqa: E501


        :return: The material_package of this DMS1TypePartition.  # noqa: E501
        :rtype: list[DMS1TypeMaterialPackage]
        """
        return self._material_package

    @material_package.setter
    def material_package(self, material_package):
        """Sets the material_package of this DMS1TypePartition.


        :param material_package: The material_package of this DMS1TypePartition.  # noqa: E501
        :type: list[DMS1TypeMaterialPackage]
        """

        self._material_package = material_package

    @property
    def offset(self):
        """Gets the offset of this DMS1TypePartition.  # noqa: E501


        :return: The offset of this DMS1TypePartition.  # noqa: E501
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this DMS1TypePartition.


        :param offset: The offset of this DMS1TypePartition.  # noqa: E501
        :type: int
        """

        self._offset = offset

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DMS1TypePartition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
