# coding: utf-8

"""
    Vidispine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.x
    Contact: info@vidispine.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six
from . import *

class DMS1TypeStaticTrack(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'dms1_framework': 'MDObjectNode'
    }

    attribute_map = {
        'dms1_framework': 'dms1Framework'
    }

    def __init__(self, dms1_framework=None):  # noqa: E501
        """DMS1TypeStaticTrack - a model defined in OpenAPI"""  # noqa: E501

        self._dms1_framework = None
        self.discriminator = None

        self.dms1_framework = dms1_framework

    @property
    def dms1_framework(self):
        """Gets the dms1_framework of this DMS1TypeStaticTrack.  # noqa: E501


        :return: The dms1_framework of this DMS1TypeStaticTrack.  # noqa: E501
        :rtype: MDObjectNode
        """
        return self._dms1_framework

    @dms1_framework.setter
    def dms1_framework(self, dms1_framework):
        """Sets the dms1_framework of this DMS1TypeStaticTrack.


        :param dms1_framework: The dms1_framework of this DMS1TypeStaticTrack.  # noqa: E501
        :type: MDObjectNode
        """
        if dms1_framework is None:
            raise ValueError("Invalid value for `dms1_framework`, must not be `None`")  # noqa: E501

        self._dms1_framework = dms1_framework

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DMS1TypeStaticTrack):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
