# coding: utf-8

"""
    Vidispine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.x
    Contact: info@vidispine.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six
from . import *

class EssenceMappingsType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'storage': 'list[StorageMappingType]',
        'asset': 'list[AssetMappingType]',
        'file': 'list[FileMappingType]'
    }

    attribute_map = {
        'storage': 'storage',
        'asset': 'asset',
        'file': 'file'
    }

    def __init__(self, storage=None, asset=None, file=None):  # noqa: E501
        """EssenceMappingsType - a model defined in OpenAPI"""  # noqa: E501

        self._storage = None
        self._asset = None
        self._file = None
        self.discriminator = None

        if storage is not None:
            self.storage = storage
        if asset is not None:
            self.asset = asset
        if file is not None:
            self.file = file

    @property
    def storage(self):
        """Gets the storage of this EssenceMappingsType.  # noqa: E501


        :return: The storage of this EssenceMappingsType.  # noqa: E501
        :rtype: list[StorageMappingType]
        """
        return self._storage

    @storage.setter
    def storage(self, storage):
        """Sets the storage of this EssenceMappingsType.


        :param storage: The storage of this EssenceMappingsType.  # noqa: E501
        :type: list[StorageMappingType]
        """

        self._storage = storage

    @property
    def asset(self):
        """Gets the asset of this EssenceMappingsType.  # noqa: E501


        :return: The asset of this EssenceMappingsType.  # noqa: E501
        :rtype: list[AssetMappingType]
        """
        return self._asset

    @asset.setter
    def asset(self, asset):
        """Sets the asset of this EssenceMappingsType.


        :param asset: The asset of this EssenceMappingsType.  # noqa: E501
        :type: list[AssetMappingType]
        """

        self._asset = asset

    @property
    def file(self):
        """Gets the file of this EssenceMappingsType.  # noqa: E501


        :return: The file of this EssenceMappingsType.  # noqa: E501
        :rtype: list[FileMappingType]
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this EssenceMappingsType.


        :param file: The file of this EssenceMappingsType.  # noqa: E501
        :type: list[FileMappingType]
        """

        self._file = file

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EssenceMappingsType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
