# coding: utf-8

"""
    Vidispine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.x
    Contact: info@vidispine.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six
from . import *

class ItemRelationType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'direction': 'ItemRelationTypeDirection',
        'id': 'str',
        'value': 'list[ItemRelationTypeValue]'
    }

    attribute_map = {
        'direction': 'direction',
        'id': 'id',
        'value': 'value'
    }

    def __init__(self, direction=None, id=None, value=None):  # noqa: E501
        """ItemRelationType - a model defined in OpenAPI"""  # noqa: E501

        self._direction = None
        self._id = None
        self._value = None
        self.discriminator = None

        self.direction = direction
        self.id = id
        if value is not None:
            self.value = value

    @property
    def direction(self):
        """Gets the direction of this ItemRelationType.  # noqa: E501


        :return: The direction of this ItemRelationType.  # noqa: E501
        :rtype: ItemRelationTypeDirection
        """
        return self._direction

    @direction.setter
    def direction(self, direction):
        """Sets the direction of this ItemRelationType.


        :param direction: The direction of this ItemRelationType.  # noqa: E501
        :type: ItemRelationTypeDirection
        """
        if direction is None:
            raise ValueError("Invalid value for `direction`, must not be `None`")  # noqa: E501

        self._direction = direction

    @property
    def id(self):
        """Gets the id of this ItemRelationType.  # noqa: E501


        :return: The id of this ItemRelationType.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ItemRelationType.


        :param id: The id of this ItemRelationType.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def value(self):
        """Gets the value of this ItemRelationType.  # noqa: E501


        :return: The value of this ItemRelationType.  # noqa: E501
        :rtype: list[ItemRelationTypeValue]
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ItemRelationType.


        :param value: The value of this ItemRelationType.  # noqa: E501
        :type: list[ItemRelationTypeValue]
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ItemRelationType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
