# coding: utf-8

"""
    Vidispine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.x
    Contact: info@vidispine.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six
from . import *

class SequenceDefinitionType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'sequence_metadata': 'SequenceMetaDataType',
        'file_sequence': 'FileSequestionDefinitionType'
    }

    attribute_map = {
        'sequence_metadata': 'sequenceMetadata',
        'file_sequence': 'fileSequence'
    }

    def __init__(self, sequence_metadata=None, file_sequence=None):  # noqa: E501
        """SequenceDefinitionType - a model defined in OpenAPI"""  # noqa: E501

        self._sequence_metadata = None
        self._file_sequence = None
        self.discriminator = None

        if sequence_metadata is not None:
            self.sequence_metadata = sequence_metadata
        self.file_sequence = file_sequence

    @property
    def sequence_metadata(self):
        """Gets the sequence_metadata of this SequenceDefinitionType.  # noqa: E501


        :return: The sequence_metadata of this SequenceDefinitionType.  # noqa: E501
        :rtype: SequenceMetaDataType
        """
        return self._sequence_metadata

    @sequence_metadata.setter
    def sequence_metadata(self, sequence_metadata):
        """Sets the sequence_metadata of this SequenceDefinitionType.


        :param sequence_metadata: The sequence_metadata of this SequenceDefinitionType.  # noqa: E501
        :type: SequenceMetaDataType
        """

        self._sequence_metadata = sequence_metadata

    @property
    def file_sequence(self):
        """Gets the file_sequence of this SequenceDefinitionType.  # noqa: E501


        :return: The file_sequence of this SequenceDefinitionType.  # noqa: E501
        :rtype: FileSequestionDefinitionType
        """
        return self._file_sequence

    @file_sequence.setter
    def file_sequence(self, file_sequence):
        """Sets the file_sequence of this SequenceDefinitionType.


        :param file_sequence: The file_sequence of this SequenceDefinitionType.  # noqa: E501
        :type: FileSequestionDefinitionType
        """
        if file_sequence is None:
            raise ValueError("Invalid value for `file_sequence`, must not be `None`")  # noqa: E501

        self._file_sequence = file_sequence

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SequenceDefinitionType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
