# coding: utf-8

"""
    Vidispine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.x
    Contact: info@vidispine.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six
from . import *

class SuggestionSearchType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'maximum_suggestions': 'int',
        'accuracy': 'float'
    }

    attribute_map = {
        'maximum_suggestions': 'maximumSuggestions',
        'accuracy': 'accuracy'
    }

    def __init__(self, maximum_suggestions=None, accuracy=None):  # noqa: E501
        """SuggestionSearchType - a model defined in OpenAPI"""  # noqa: E501

        self._maximum_suggestions = None
        self._accuracy = None
        self.discriminator = None

        if maximum_suggestions is not None:
            self.maximum_suggestions = maximum_suggestions
        if accuracy is not None:
            self.accuracy = accuracy

    @property
    def maximum_suggestions(self):
        """Gets the maximum_suggestions of this SuggestionSearchType.  # noqa: E501


        :return: The maximum_suggestions of this SuggestionSearchType.  # noqa: E501
        :rtype: int
        """
        return self._maximum_suggestions

    @maximum_suggestions.setter
    def maximum_suggestions(self, maximum_suggestions):
        """Sets the maximum_suggestions of this SuggestionSearchType.


        :param maximum_suggestions: The maximum_suggestions of this SuggestionSearchType.  # noqa: E501
        :type: int
        """

        self._maximum_suggestions = maximum_suggestions

    @property
    def accuracy(self):
        """Gets the accuracy of this SuggestionSearchType.  # noqa: E501


        :return: The accuracy of this SuggestionSearchType.  # noqa: E501
        :rtype: float
        """
        return self._accuracy

    @accuracy.setter
    def accuracy(self, accuracy):
        """Sets the accuracy of this SuggestionSearchType.


        :param accuracy: The accuracy of this SuggestionSearchType.  # noqa: E501
        :type: float
        """

        self._accuracy = accuracy

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SuggestionSearchType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
