# coding: utf-8

"""
    Vidispine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.x
    Contact: info@vidispine.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six
from . import *

class SystemInfoType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'database_size': 'int',
        'macaddress': 'list[str]'
    }

    attribute_map = {
        'database_size': 'databaseSize',
        'macaddress': 'macaddress'
    }

    def __init__(self, database_size=None, macaddress=None):  # noqa: E501
        """SystemInfoType - a model defined in OpenAPI"""  # noqa: E501

        self._database_size = None
        self._macaddress = None
        self.discriminator = None

        if database_size is not None:
            self.database_size = database_size
        if macaddress is not None:
            self.macaddress = macaddress

    @property
    def database_size(self):
        """Gets the database_size of this SystemInfoType.  # noqa: E501


        :return: The database_size of this SystemInfoType.  # noqa: E501
        :rtype: int
        """
        return self._database_size

    @database_size.setter
    def database_size(self, database_size):
        """Sets the database_size of this SystemInfoType.


        :param database_size: The database_size of this SystemInfoType.  # noqa: E501
        :type: int
        """

        self._database_size = database_size

    @property
    def macaddress(self):
        """Gets the macaddress of this SystemInfoType.  # noqa: E501


        :return: The macaddress of this SystemInfoType.  # noqa: E501
        :rtype: list[str]
        """
        return self._macaddress

    @macaddress.setter
    def macaddress(self, macaddress):
        """Sets the macaddress of this SystemInfoType.


        :param macaddress: The macaddress of this SystemInfoType.  # noqa: E501
        :type: list[str]
        """

        self._macaddress = macaddress

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemInfoType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
