# coding: utf-8

"""
    Vidispine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.x
    Contact: info@vidispine.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six
from . import *

class TaskDefinitionListType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'task': 'list[TaskDefinitionType]',
        'metadata': 'SimpleMetadataType'
    }

    attribute_map = {
        'task': 'task',
        'metadata': 'metadata'
    }

    def __init__(self, task=None, metadata=None):  # noqa: E501
        """TaskDefinitionListType - a model defined in OpenAPI"""  # noqa: E501

        self._task = None
        self._metadata = None
        self.discriminator = None

        if task is not None:
            self.task = task
        if metadata is not None:
            self.metadata = metadata

    @property
    def task(self):
        """Gets the task of this TaskDefinitionListType.  # noqa: E501


        :return: The task of this TaskDefinitionListType.  # noqa: E501
        :rtype: list[TaskDefinitionType]
        """
        return self._task

    @task.setter
    def task(self, task):
        """Sets the task of this TaskDefinitionListType.


        :param task: The task of this TaskDefinitionListType.  # noqa: E501
        :type: list[TaskDefinitionType]
        """

        self._task = task

    @property
    def metadata(self):
        """Gets the metadata of this TaskDefinitionListType.  # noqa: E501


        :return: The metadata of this TaskDefinitionListType.  # noqa: E501
        :rtype: SimpleMetadataType
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this TaskDefinitionListType.


        :param metadata: The metadata of this TaskDefinitionListType.  # noqa: E501
        :type: SimpleMetadataType
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaskDefinitionListType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
